name: MyBuild



on: [push]



jobs:

  build:



    runs-on: windows



    steps:

    - uses: actions/checkout@v2

    - name: Run a one-line script

      run: echo Hello, Grs!

    - name: Run a multi-line script

      run: |echo Hello, Grs1!

        echo Hello, Grs2!

        echo Add other actions to build,

        echo test, and deploy your project.
